### ISSUE TITLE
How to disable `tpa` separately

### ISSUE THREAD

**Issue by lakuhana** [Maciej916/Ma-Essentials#90]
```toml
[Commands.tpa]
		#Enable commands: /tpa, /tpahere, /tpaccept, /tpdeny
		enable = false
		#Range: > 0
		delay = 3
		#Range: > 0
		cooldown = 0
		#Range: > 0
		timeout = 20
```
/tpa, /tpahere, /tpaccept, /tpdeny is closed together,but I want /tpg not others. How I can?
